deploy: Migrate from Deploy Classic to Deno Deploy
Deno Deploy Classic will be shut down on July 20, 2026 [1]. As such
deployctl cannot be used anymore, and the new `deno deploy` command has
to be used.

With this migration, a couple of other related changes are being done
for best practice.

Deno Deploy
===========

Switch from `deployctl` to `deno deploy`. With this a couple of
noteworthy choices are being done

Workflow
--------

This migration keeps the GitHub Workflow, as opposed to using the Deno
Deploy integration. This is done to keep better control over the deploy
process, be able to run tests before deployment, and to not
vendor-lockin too much into GitHub in case a migration happens.

Region US
---------

Discord itself is hosted in the US, and as such the discord bot will be
hosted in the US as well. As no user data is stored, the choice between
regions isn't all that relevant.

Memory limits
-------------

There is no build process, everything is being done at runtime. As such
keep it as low as it can go.

Create + Environment Variables
------------------------------

The whole application creation process is done in the action, to be
consistent and reproducible. As opposed to being done by a human with a
mouse and keyboard.

In addition, make a new dummy file with environment variables and fill
it out with the relevant variables during the deploy process. This is
also done to be consistent and reproducible.

GitHub Workflow
===============

Major overhaul of the GitHub Workflow.

Upgrades
--------

A couple of actions have been updated, and with them new parameters that
speed up or improve the workflow have been used.

In addition, make it so that a workflow can be started directly from
GitHub's Web UI.

Testing
-------

Add GitHub Actions linting and require that both code checks and
workflow linting pass before deployment.

Zizmor is used for linting and it is set to be as strict as possible.

Security
--------

Zizmor [2] is a tool that lints GitHub Actions Workflows and it catches a
couple of security and best practice issues with the workflow, as such
these are fixed. In particular:

- Stricter permissions.
- Pin github actions dependencies by git hash.
- Set up `concurrency`, and in particular cancellation when appropriate.

[1]: https://docs.deno.com/deploy/migration_guide/
[2]: https://docs.zizmor.sh/

diff --git a/.github/workflows/deno.yml b/.github/workflows/deno.yml
--- a/.github/workflows/deno.yml
+++ b/.github/workflows/deno.yml
@@ -1,4 +1,6 @@
-name: Deno
+name: CI / CD
+
+permissions: {}
 
 on:
   push:
@@ -6,18 +8,50 @@ on:
   pull_request:
     branches: [master]
 
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
 jobs:
+  zizmor:
+    name: Run zizmor
+    runs-on: ubuntu-latest
+    concurrency:
+      group: zizmor-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+      cancel-in-progress: true
+
+    permissions:
+      security-events: write # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+        with:
+          persist-credentials: false
+
+      - name: Run zizmor
+        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
+        with:
+          persona: auditor
+
   test:
     runs-on: ubuntu-latest
+    name: Test
+    concurrency:
+      group: test-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+      cancel-in-progress: true
+
+    permissions: {}
 
     steps:
       - name: Setup repo
-        uses: actions/checkout@v2
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
+        with:
+          persist-credentials: false
 
       - name: Setup Deno
-        uses: denoland/setup-deno@v1
+        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # 2.0.4
         with:
-          deno-version: v2.x
+          deno-version: "^2"
+          cache: true
 
       - name: Run checks
         run: deno task ci
@@ -25,41 +59,71 @@ jobs:
   publish:
     if: github.repository == 'AnInternetTroll/speedrunbot-slash' && github.ref == 'refs/heads/master'
     runs-on: ubuntu-latest
+    needs: [test, zizmor]
+    environment: production
+    name: Deploy
+    concurrency:
+      group: deploy-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+      # Finish deploying, don't leave in an unknown state
+      cancel-in-progress: false
+
+    permissions: {}
 
     env:
       TOKEN: ${{ secrets.TOKEN }}
       PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
       CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
       DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
-      PROJECT_NAME: "speedrunbot"
+      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
+      DENO_DEPLOY_ORGANISATION_NAME: ${{ secrets.DENO_DEPLOY_ORGANISATION_NAME }}
 
     steps:
       - name: Setup repo
-        uses: actions/checkout@v2
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
+        with:
+          persist-credentials: false
 
       - name: Setup Deno
-        uses: denoland/setup-deno@v1
+        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # 2.0.4
         with:
-          deno-version: v2.x
+          deno-version: "^2"
+          cache: true
+
+      - name: Create
+        run: |
+          deno deploy create \
+                --org "${DENO_DEPLOY_ORGANISATION_NAME}" \
+                --app "${PROJECT_NAME}" \
+                --source local \
+                --do-not-use-detected-build-config \
+                --runtime-mode dynamic \
+                --entrypoint="./main.ts" \
+                --region us \
+                --install-command "deno install" \
+                --build-timeout 5 \
+                --build-memory-limit 1024 \
+                --no-wait || exit 0
+                # Allow command to fail, as the project may exist already
+                # Next step should fail if this failed for other reasons
+
+      - name: Environment variables
+        run: |
+          envsubst < ".env.deploy" > ".env.deploy-output"
+          deno deploy env load ".env.deploy-output" \
+                --org "${DENO_DEPLOY_ORGANISATION_NAME}" \
+                --app "${PROJECT_NAME}" \
+                --token="${DENO_DEPLOY_TOKEN}" \
+                --replace \
+                --non-secrets "PUBLIC_KEY" "TEST_SERVER"
+          rm  ".env.deploy-output"
 
       - name: Deploy
         run: |
-          deno install -gArf jsr:@deno/deployctl
-
-          deployctl deploy \
-            --prod \
-            --color=never \
-            --entrypoint="./main.ts" \
-            --project=$PROJECT_NAME \
-            --env=CLIENT_SECRET=$CLIENT_SECRET \
-            --env=PUBLIC_KEY=$PUBLIC_KEY \
-            --env=TOKEN=$TOKEN
-
-          deployment_id="$(deployctl deployments list --project $PROJECT_NAME --format=json | jq -r '. |= sort_by(.createdAt) | reverse | .[].deployment.id' | head -n 1)"
-          deployctl deployments redeploy \
-            --prod \
-            --project=$PROJECT_NAME \
-            --id="$deployment_id"
+          deno deploy \
+                --prod \
+                --org "${DENO_DEPLOY_ORGANISATION_NAME}" \
+                --app "${PROJECT_NAME}" \
+                --token="${DENO_DEPLOY_TOKEN}"
 
       - name: Update commands
         run: deno run --allow-all main.ts -u
