Deploy to new deno deploy

diff --git a/.github/workflows/deno.yml b/.github/workflows/deno.yml
--- a/.github/workflows/deno.yml
+++ b/.github/workflows/deno.yml
@@ -1,5 +1,4 @@
 name: Deno
-
 on:
   push:
     branches: [master]
@@ -12,54 +11,77 @@ jobs:
 
     steps:
       - name: Setup repo
-        uses: actions/checkout@v2
+        # 6.0.2
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
 
       - name: Setup Deno
-        uses: denoland/setup-deno@v1
+        # 2.0.4
+        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282
         with:
-          deno-version: v2.x
+          deno-version: "^2"
 
       - name: Run checks
         run: deno task ci
 
   publish:
-    if: github.repository == 'AnInternetTroll/speedrunbot-slash' && github.ref == 'refs/heads/master'
+    if: github.repository == 'AnInternetTroll/speedrunbot-slash-deno-deploy-2' && github.ref == 'refs/heads/master'
     runs-on: ubuntu-latest
+    needs: [test]
 
     env:
       TOKEN: ${{ secrets.TOKEN }}
       PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
       CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
       DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
-      PROJECT_NAME: "speedrunbot"
+      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
+      DENO_DEPLOY_ORGANISATION_NAME: ${{ secrets.DENO_DEPLOY_ORGANISATION_NAME }}
 
     steps:
       - name: Setup repo
-        uses: actions/checkout@v2
+        # 6.0.2
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
 
       - name: Setup Deno
-        uses: denoland/setup-deno@v1
+        # 2.0.4
+        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282
         with:
-          deno-version: v2.x
+          deno-version: "^2"
+
+      - name: Create
+        run: |
+          deno deploy create \
+                --org "${DENO_DEPLOY_ORGANISATION_NAME}" \
+                --app "${PROJECT_NAME}" \
+                --source local \
+                --do-not-use-detected-build-config \
+                --runtime-mode dynamic \
+                --entrypoint="./main.ts" \
+                --region us \
+                --install-command "deno install" \
+                --build-timeout 5 \
+                --build-memory-limit 1024 \
+                --no-wait || exit 0
+                # Allow command to fail, as the project may exist already
+                # Next step should fail if this failed for other reasons
+
+      - name: Environment variables
+        run: |
+          envsubst < ".env.deploy" > ".env.deploy-output"
+          deno deploy env load ".env.deploy-output" \
+                --org "${DENO_DEPLOY_ORGANISATION_NAME}" \
+                --app "${PROJECT_NAME}" \
+                --token="${DENO_DEPLOY_TOKEN}" \
+                --replace \
+                --non-secrets "PUBLIC_KEY" "TEST_SERVER"
+          rm  ".env.deploy-output"
 
       - name: Deploy
         run: |
-          deno install -gArf jsr:@deno/deployctl
-
-          deployctl deploy \
-            --prod \
-            --color=never \
-            --entrypoint="./main.ts" \
-            --project=$PROJECT_NAME \
-            --env=CLIENT_SECRET=$CLIENT_SECRET \
-            --env=PUBLIC_KEY=$PUBLIC_KEY \
-            --env=TOKEN=$TOKEN
-
-          deployment_id="$(deployctl deployments list --project $PROJECT_NAME --format=json | jq -r '. |= sort_by(.createdAt) | reverse | .[].deployment.id' | head -n 1)"
-          deployctl deployments redeploy \
-            --prod \
-            --project=$PROJECT_NAME \
-            --id="$deployment_id"
+          deno deploy \
+                --prod \
+                --org "${DENO_DEPLOY_ORGANISATION_NAME}" \
+                --app "${PROJECT_NAME}" \
+                --token="${DENO_DEPLOY_TOKEN}"
 
       - name: Update commands
         run: deno run --allow-all main.ts -u
